baseurl: https://nick-kachanyuk-website.netlify.app/
title: Nick Kachanyuk
author: Nick Kachanyuk
canonifyurls: yes
languagecode: en
theme: hugo-tanka
enableEmoji: yes
hasCJKLanguage: no
pygmentsstyle: vs
pygmentscodefences: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
params:
  faviconfile: images/favicon.png
  highlightjs: yes
  highlightjslanguages:
    - r
    - python
    - stan
  progressively: no
  sitename: Nick Kachanyuk
  uselatex: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
menu:
  primary:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: GitHub
      url: https://github.com/nickkachanyuk
      weight: 3
    - name: Medium
      url: https://nkachanyuk123.medium.com/
      weight: 4
    - name: Subscribe
      url: /index.xml
      weight: 5
