---
title: Elevator pitch
author: Nick Kachanyuk
date: '2021-06-09'
slug: []
categories:
  - R
tags:
  - R Markdown
meta_img: images/image.png
description: Description for the page
---

According to Water.org, Tanzania is experiencing a water and sanitation crisis. According to their records 4 million people lack access to safe water resources. People often spend a significant amount of time traveling long distances to collect water, and this burden often falls on women and girls. There is an opportunity to explore the water crisis in Tanzania. Using the data provided for the Pump it Up competition by DrivenData along with Tanzania's 2012 census report, it is possible to not only identify functionality of the water pumps in Tanzania but also identify socioeconomic indicators of the different regions that are contributing to the water crisis in Tanzania. Using data aggregation and machine learning techniques, the goal of this project is to identify water well functionality (functional, needs repairs, non-functional) and the socioeconomic factors (population, household composition, economic activity, etc) that may be contributing to the water crisis in a given region of Tanzania.